# Generated by Django 2.2.3 on 2019-11-28 18:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_auto_20191127_2232'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='bestseller',
        ),
    ]
