# Generated by Django 2.2.4 on 2020-02-18 21:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_remove_item_bestseller'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='average_rating',
            field=models.FloatField(default=1),
            preserve_default=False,
        ),
    ]
