# Generated by Django 2.2.4 on 2020-02-18 21:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_item_average_rating'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='average_rating',
        ),
    ]
